Unhandled exception in XMPP recv.
The following was in the user.log.

Traceback (most recent call last):
012  File "/usr/share/cloudprint/cloudprint/cloudprint.py", line 373, in process_jobs
012    xmpp_conn.await_notification(sleeptime)
012  File "/usr/share/cloudprint/cloudprint/xmpp.py", line 189, in await_notification
012    self._read_socket()
012  File "/usr/share/cloudprint/cloudprint/xmpp.py", line 55, in _read_socket
012    data = self._wrappedsock.recv(1024)
012  File "/usr/lib/python2.7/ssl.py", line 305, in recv
012    return self.read(buflen)
012  File "/usr/lib/python2.7/ssl.py", line 224, in read
012    return self._sslobj.read(len)
012error: [Errno 104] Connection reset by peer

Assume that this is because the exception is not of type 'Exception',
and change the except in process_jobs to pure except:.
(cherry picked from commit a7cdfdb1fca55cf8d83698f49945f60aef5f9adc)

Fixes #28 - cloudprint crashes unpredictably in gentoo